In [1]:
import numpy as np

x_1 = np.arange(1, 7).reshape(2, 3)
x_2 = np.arange(1, 7).reshape(3, 2)

print(x_1)
print(x_2)

print(x_1.dot(x_2))
# [[22 28]
#  [49 64]]

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [12]:
x_1 = np.arange(1, 11).reshape(2, 5)
x_2 = np.arange(1, 16).reshape(5, -1)

print(x_1.dot(x_2))
# [[135 150 165]
#  [310 350 390]]

[[135 150 165]
 [310 350 390]]


In [24]:
x = np.arange(1, 10).reshape(3, 3)

print(x + 10)
# [[11 12 13]
#  [14 15 16]
#  [17 18 19]]

print(x - 10)
# [[-9 -8 -7]
#  [-6 -5 -4]
#  [-3 -2 -1]]

print(x / 10)
# [[0.1 0.2 0.3]
#  [0.4 0.5 0.6]
#  [0.7 0.8 0.9]]

print(x * 10)
# [[10 20 30]
#  [40 50 60]
#  [70 80 90]]

print(x % 2)
# [[1 0 1]
#  [0 1 0]
#  [1 0 1]]

print(x + [10])
# [[11 12 13]
#  [14 15 16]
#  [17 18 19]]

print(x + [10, 11])
# ERROR

print(x + [10, 11, 12])

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 13 15]
 [14 16 18]
 [17 19 21]]


In [27]:
x = np.arange(1, 13).reshape(4, 3)
v = np.arange(10, 40, 10)

print(x + v)
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]
#  [20 31 42]]

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [2]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iteration_max = 100000000
vector = list(range(iteration_max))
scalar = 2

In [3]:
# for문을 이용한 성능
%timeit sclar_vector_product(scalar, vector)

10.6 s ± 554 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
# 리스트 컴프리헨션을 이용한 성능
%timeit [scalar * value for value in range(iteration_max)]

8.39 s ± 474 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# 넘파이를 이용한 성능
%timeit np.arange(iteration_max) * scalar

470 ms ± 19.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iteration_max = 100000000
vector = list(range(iteration_max))
scalar = 2


%timeit sclar_vector_product(scalar, vector)

%timeit [scalar * value for value in range(iteration_max)]

%timeit np.arange(iteration_max) * scalar

In [8]:
x = np.array([4, 3, 2, 6, 8, 5])
print(x > 3)

# [ True False False  True  True  True]

[ True False False  True  True  True]


In [9]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])

print(x > y)
# [False  True False]

[False  True False]


In [12]:
x = np.array([4, 6, 7, 3, 2])
print(x > 3)
# [ True  True  True False False]

print((x > 3).all())
# False

print((x > 3).any())
# True

print((x < 10).any())
# True

print((x < 10).all())
# True

print((x > 10).any())
# False

[ True  True  True False False]
False
True
True
True
False


In [16]:
x = np.array([4, 6, 7, 3, 2])
print(x > 5)
# [False  True  True False False]

print(np.where(x > 5))
# (array([1, 2]),)

print((np.where(x>5, 10, 20))) # 조건이 참이면 10, 거짓이면 20 반환.
# [20 10 10 20 20]

[False  True  True False False]
(array([1, 2]),)
[20 10 10 20 20]


In [20]:
x = np.array([4, 6, 7, 3, 2])
print(np.argsort(x))
#[4 3 0 1 2] 

print(np.argmax(x))
# 2

print(np.argmin(x))
# 4

[4 3 0 1 2]
2
4


In [23]:
x = np.array([4, 6, 7, 3, 2])
cond = x > 3

print(x[cond])
# [4 6 7]

print(x.shape)
# (5,)

print(cond.shape)
# (5,)

[4 6 7]
(5,)
(5,)


In [29]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)

print(x[cond])
# [6 7 4 7 7 7]

print(x.take(cond))
# [6 7 4 7 7 7]

x = np.array([[1, 4], [9, 16]], int)
a = np.array([0, 1, 1, 1, 0, 0] , int)
b = np.array([0, 0, 0, 1, 1, 1], int)
print(x[a, b])
# [ 1  9  9 16  4  4]

[6 7 4 7 7 7]
[6 7 4 7 7 7]
[ 1  9  9 16  4  4]


In [30]:
import pandas as pd

In [31]:
list_data = [1, 2, 3, 4, 5]
example_obj = pd.Series(list_data)

print(example_obj)
# 0    1
# 1    2
# 2    3
# 3    4
# 4    5
# dtype: int64

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [32]:
list_data = [1, 2, 3, 4, 5]
list_name = ["a",  "b", "c", "d", "e"]
example_obj = pd.Series(data = list_data, index = list_name)

print(example_obj)
# a    1
# b    2
# c    3
# d    4
# e    5
# dtype: int64

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [36]:
dict_data_1 = {"a" : 1, "b":2, "c":3, "d":4, "e":5}

indexex = ["a", "b", "c", "d", "e", "f", "g", "h"]

series_obj_1 = pd.Series(dict_data_1, index=indexex)

print(series_obj_1)
# a    1.0
# b    2.0
# c    3.0
# d    4.0
# e    5.0
# f    NaN
# g    NaN
# h    NaN
# dtype: float64

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64


In [37]:
dict_data = {"a" : 1, "b":2, "c":3, "d":4, "e":5}

series_obj_1 = pd.Series(dict_data, dtype = np.float32)

print(series_obj_1)
# a    1.0
# b    2.0
# c    3.0
# d    4.0
# e    5.0
# dtype: float32

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float32


In [39]:
dict_data = {"a" : 1, "b":2, "c":3, "d":4, "e":5}

example_obj = pd.Series(dict_data, dtype = np.float32, name = "example_data")

print(example_obj)
# a    1.0
# b    2.0
# c    3.0
# d    4.0
# e    5.0
# Name: example_data, dtype: float32

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32


In [45]:
print(example_obj.values)
# [1. 2. 3. 4. 5.]

print(example_obj.index)
# Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

print(example_obj.dtype)
# float32

print(type(example_obj.values))
# <class 'numpy.ndarray'>

[1. 2. 3. 4. 5.]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
float32
<class 'numpy.ndarray'>


In [46]:
example_obj.name = "number"
example_obj.index.name = "id"
example_obj

# id
# a    1.0
# b    2.0
# c    3.0
# d    4.0
# e    5.0
# Name: number, dtype: float32

id
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: number, dtype: float32

In [66]:
# series_obj_1의 1번째 원소를 선택 합니다.
print(series_obj_1[1])
# 2.0


# b라벨을 가진 원소를 선택합니다.
print(series_obj_1["b"])
# 2.0


# c와 e원소를 선택합니다.
print(series_obj_1[["c", "e"]])
print(series_obj_1[[2, 4]])
# c    3.0
# e    5.0
# dtype: float32


# b에서 d까지의 원소를 선택합니다.
print(series_obj_1['b':'d']) # 별칭을 타겟으로 지정 할 경우 미만의 개념이 없습니다.
print(series_obj_1[1:4])
# b    2.0
# c    3.0
# d    4.0
# dtype: float32

2.0
2.0
c    3.0
e    5.0
dtype: float32
c    3.0
e    5.0
dtype: float32
b    2.0
c    3.0
d    4.0
dtype: float32
b    2.0
c    3.0
d    4.0
dtype: float32


In [79]:
table = {"나이" : [15, 17],
        "성별" : ['남', "여"],
        "학교" : ["덕영중", "수리중"]}

pd.DataFrame(table, index=["준서","예은"])

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [82]:
# 두개의 벡터로 생성
v1 = [15, '남', '덕영중']
v2 = [17, '여', '수리중']
pd.DataFrame([v1, v2], columns=["나이", "성별", "학교"], index=["준서", "예은"])

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [93]:
raw_data = {'first_name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
            'last_name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze'],
            'age': [42, 52, 36, 24, 73],
            'city': ['San Francisco', 'Baltimore', 'Miami', 'Douglas', 'Boston']}

df = pd.DataFrame(raw_data)

print(df.index)
# RangeIndex(start=0, stop=5, step=1)

print(df.columns)
# Index(['first_name', 'last_name', 'age', 'city'], dtype='object')

print(df.columns[3])
# city

RangeIndex(start=0, stop=5, step=1)
Index(['first_name', 'last_name', 'age', 'city'], dtype='object')
city


In [94]:
pd.DataFrame(raw_data, columns = ["age", "city"])

age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

In [95]:
pd.DataFrame(raw_data, columns = ["age", "city", "debt"])

age           city debt
0   42  San Francisco  NaN
1   52      Baltimore  NaN
2   36          Miami  NaN
3   24        Douglas  NaN
4   73         Boston  NaN

In [100]:
df = pd.DataFrame(raw_data)

df.index = ["student1", "student2", "student3", "student4", "student5"]
df.columns = ['이름', "성", "나이", "지역"]

print(df)
#              이름         성  나이             지역
# student1  Jason    Miller  42  San Francisco
# student2  Molly  Jacobson  52      Baltimore
# student3   Tina       Ali  36          Miami
# student4   Jake    Milner  24        Douglas
# student5    Amy     Cooze  73         Boston

print(df.index)
print(df.columns)

             이름         성  나이             지역
student1  Jason    Miller  42  San Francisco
student2  Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston
Index(['student1', 'student2', 'student3', 'student4', 'student5'], dtype='object')
Index(['이름', '성', '나이', '지역'], dtype='object')


In [113]:
# 컬럼 이름중 '나이'를 '연령'으로 '지역'을 '도시'로 변경합니다.
df.rename(columns = {"나이" : "연령", "지역" : "도시"}, inplace = True)

#행 인덱스 중에서 'student1'을 '학생1'로 변경합니다.
df.rename(index={'student1' : "학생1"}, inplace = True)

# axis의 값이 기본 값이 0이기 때문에 'index=' 입력하지 않아도 index가 변경됩니다.
df.rename({'student2' : "학생2"})



이름         성  연령             도시
학생1       Jason    Miller  42  San Francisco
학생2       Molly  Jacobson  52      Baltimore
student3   Tina       Ali  36          Miami
student4   Jake    Milner  24        Douglas
student5    Amy     Cooze  73         Boston

In [114]:
!conda install --y openpyxl

Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/osx-64::anaconda==2022.05=py39_0
  - defaults/osx-64::bcrypt==3.2.0=py39h9ed2024_0
  - defaults/osx-64::scrapy==2.6.1=py39hecd8cb5_0
  - defaults/osx-64::twisted==22.2.0=py39hca72f7f_0
done

## Package Plan ##

  environment location: /Users/werther/opt/anaconda3

  added / updated specs:
    - openpyxl


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-2022.05  |           py39_0           7 KB
    anaconda-custom            |           py39_1           4 KB
    certifi-2022.9.14          |   py39hecd8cb5_0         156 KB
    openpyxl-3.0.10            |   py39hca72f7f_0         505 KB
    pip-22.1.2                 |   py39hecd8cb5_0         2.4 MB
    -------------------------------------------------------

In [117]:
import pandas as pd
import numpy as np
df = pd.read_excel("./excel-comp-data.xlsx")

In [121]:
df.head()
df.head(2)
df.tail()
df.tail(2)
df.tail()

account                          name                     street  \
10   214098   Goodwin, Homenick and Jerde  649 Cierra Forks Apt. 078   
11   231907                    Hahn-Moore   18115 Olivine Throughway   
12   242368  Frami, Anderson and Donnelly            182 Bertie Road   
13   268755                   Walsh-Haley       2624 Beatty Parkways   
14   273274                 McDermott PLC      8917 Bergstrom Meadow   

               city        state  postal-code     Jan     Feb     Mar  
10         Rosaberg     Tenessee        47743   45000  120000   55000  
11    Norbertomouth  NorthDakota        31415  150000   10000  162000  
12      East Davian         Iowa        72686  162000  120000   35000  
13     Goodwinmouth  RhodeIsland        31919   55000  120000   35000  
14  Kathryneborough     Delaware        27933  150000  120000   70000

In [124]:
df[["account", "street", "state"]].head(3)

account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [126]:
df["account"].head(3)

# 0    211829
# 1    320563
# 2    648336
# Name: account, dtype: int64

0    211829
1    320563
2    648336
Name: account, dtype: int64

In [128]:
df.account.head(3) # df['account'].head(3)

# 0    211829
# 1    320563
# 2    648336
# Name: account, dtype: int64

0    211829
1    320563
2    648336
Name: account, dtype: int64