In [2]:
import numpy as np

In [6]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]


In [7]:
np.array(test_list, float) #ValueError

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [10]:
type(test_array[3])

numpy.float64

In [18]:
test_array = np.array([1, 4, 5, '8'], float)

print(test_array)
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

# [1. 4. 5. 8.]
# <class 'numpy.float64'>
# float64
# (4,)

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [15]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]

np.array(matrix, int).shape
# (3, 4)

(3, 4)

In [20]:
matrix = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
         [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
         [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]

print(np.array(matrix, int).shape)
print(np.array(matrix, int).ndim) #number of dimension
print(np.array(matrix, int).size) 
# (3, 3, 4)
# 3
# 36

(3, 3, 4)
3
36


In [21]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = int)
# array([[1, 2, 3],
#        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = float)

# array([[1. , 2. , 3.5],
#        [4. , 5. , 6.5]])

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [26]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = np.float32).itemsize
# 4



8

In [27]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype = np.float64).itemsize
# 8

8

In [29]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.reshape(-1,)

# array([1, 2, 5, 8, 1, 2, 5, 8])

array([1, 2, 5, 8, 1, 2, 5, 8])

In [33]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.reshape(2, 2, 2)

# array([[[1, 2],
#         [5, 8]],
# 
#        [[1, 2],
#         [5, 8]]])

array([[[1, 2],
        [5, 8]],

       [[1, 2],
        [5, 8]]])

In [42]:
x = np.array(range(8))

x.reshape(2, -1)

# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
x.flatten()

# array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
x = np.array([[1, 2, 3], [4, 5, 6]], int)
print(x[0][2])
print(x[0,2])
# 3
# 3

3
3


In [52]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

print(x[:,2:])
# [[ 3  4  5]
#  [ 8  9 10]]

print(x[1, 1:3])
# [7 8]

print(x[1:3])
# [[ 6  7  8  9 10]]


[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [56]:
x = np.array(range(15), int).reshape(3, -1)
print(x)
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
print(x[:,::2])

# [[ 0  2  4]
#  [ 5  7  9]
#  [10 12 14]]

print(x[::2,::3])

# [[ 0  3]
#  [10 13]]

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]]


In [61]:
print(x[::2,::3])

# [[ 0  3]
#  [10 13]]

[[ 0  3]
 [10 13]]


In [64]:
print(np.arange(10))
print(np.arange(-5, 5))
print(np.arange(0, 5, 0.5))

# [0 1 2 3 4 5 6 7 8 9]
# [-5 -4 -3 -2 -1  0  1  2  3  4]
# [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]

[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [68]:
print(np.ones(shape=[5, 2], dtype=np.int8))

# [[1 1]
#  [1 1]
#  [1 1]
#  [1 1]
#  [1 1]]

print(np.zeros(shape=[2, 2], dtype=np.float32))

# [[0. 0.]
#  [0. 0.]]

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [69]:
print(np.zeros(shape=[2, 2], dtype=np.float32))

# [[0. 0.]
#  [0. 0.]]

[[0. 0.]
 [0. 0.]]


In [112]:
print(np.empty(shape=(2, 4), dtype=np.float32))

[[0.     1.875  0.     2.25  ]
 [0.     2.3125 0.     2.5   ]]


In [77]:
x = np.arange(12).reshape(3, 4)

print(x)
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]

print(np.ones_like(x))
# [[1 1 1 1]
#  [1 1 1 1]
#  [1 1 1 1]]

print(np.zeros_like(x))
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]

print(np.empty_like(x))
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [83]:
print(np.identity(n=3, dtype=int))

# [[1 0 0]
#  [0 1 0]
#  [0 0 1]]

print(np.identity(n=4, dtype=int))

#[[1 0 0 0]
# [0 1 0 0]
# [0 0 1 0]
# [0 0 0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [84]:
print(np.identity(n=4, dtype=int))

#[[1 0 0 0]
# [0 1 0 0]
# [0 0 1 0]
# [0 0 0 1]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [87]:
print(np.eye(N=3, M=5))

# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [96]:
print(np.eye(N=3, M=5, k=2))

# [[0. 0. 1. 0. 0.]
#  [0. 0. 0. 1. 0.]
#  [0. 0. 0. 0. 1.]]


[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [106]:
print(np.diag(np.arange(9).reshape(3, 3)))
# [0 4 8]

print(np.diag(np.arange(9).reshape(3, 3), k=1))
# [1 5]

[0 4 8]


In [107]:
print(np.diag(np.arange(9).reshape(3, 3), k=1))
# [1 5]

[1 5]


In [111]:
print(np.random.uniform(0, 5, 10))

# [0.52675772 0.42216318 3.88471858 2.38202763 3.23275871 2.58250078
#  3.81355672 4.66374263 1.46639956 3.29314779]

[0.52675772 0.42216318 3.88471858 2.38202763 3.23275871 2.58250078
 3.81355672 4.66374263 1.46639956 3.29314779]


In [114]:
print(np.random.normal(0, 2, 10))
# [ 1.67769499  2.65559914 -0.83006297 -0.54458485  1.96107166  1.43042317
#  -1.4927319  -1.8952236  -0.91212602  0.83006339]

[ 1.67769499  2.65559914 -0.83006297 -0.54458485  1.96107166  1.43042317
 -1.4927319  -1.8952236  -0.91212602  0.83006339]


In [152]:
x = np.random.normal(0, 2, 10)
print(np.mean(x)) # 평균
print(np.std(x)) # 표준편차
print(np.var(x)) # 분산
# 0.37585327103539473
# 1.1455876931248066
# 4.6868580082283

-0.5418771163539947
2.164915242735452
4.6868580082283


In [153]:
import numpy as np

test_array = np.arange(1, 11)
test_array.sum()
# 55

55

In [158]:
print(np.arange(1, 13).reshape(3, 4).sum(axis = None))
# 78
print(np.arange(1, 13).reshape(3, 4).sum(axis = 0)) # 컬럼 별로 더한다.
# [15 18 21 24]
print(np.arange(1, 13).reshape(3, 4).sum(axis = 1)) # 로우 별로 더한다.
# [10 26 42]

78
[15 18 21 24]
[10 26 42]


In [163]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array, test_array, test_array])
print(third_order_tensor)
# [[[ 1  2  3  4]
#   [ 5  6  7  8]
#   [ 9 10 11 12]]
#  [[ 1  2  3  4]
#   [ 5  6  7  8]
#   [ 9 10 11 12]]
#  [[ 1  2  3  4]
#   [ 5  6  7  8]
#   [ 9 10 11 12]]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [165]:
# 3차원 합


print(third_order_tensor.sum(axis = 1))
# [[15 18 21 24]
#  [15 18 21 24]
#  [15 18 21 24]]


print(third_order_tensor.sum(axis = 0))
# [[ 3  6  9 12]
#  [15 18 21 24]
#  [27 30 33 36]]


print(third_order_tensor.sum(axis = 2))
# [[10 26 42]
#  [10 26 42]
#  [10 26 42]]

[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[10 26 42]
 [10 26 42]
 [10 26 42]]


In [178]:
# print(test_array)
print(test_array.mean(axis = 1))
print(test_array.std(axis = 0))
print(np.sqrt(test_array))

# [ 2.5  6.5 10.5]
# [3.26598632 3.26598632 3.26598632 3.26598632]
# [[1.         1.41421356 1.73205081 2.        ]
#  [2.23606798 2.44948974 2.64575131 2.82842712]
#  [3. 

[ 2.5  6.5 10.5]
[3.26598632 3.26598632 3.26598632 3.26598632]
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


In [184]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

np.vstack((v1, v2))
# ([[1, 2, 3],
#   [4, 5, 6]])

np.hstack((v1, v2))
# ([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
np.hstack((v1, v2))

# ([[1, 4],
#   [2, 5],
#   [3, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [196]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])


print(np.concatenate((v1, v2)))
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [200]:
v1 = np.array([[1, 2], [3, 4]])
v2 = np.array([[5], [6]])

print(np.concatenate((v1, v2), axis=1))
# [[1 2 5]
#  [3 4 6]]

[[1 2 5]
 [3 4 6]]


In [205]:
x = np.arange(1, 7).reshape(2, 3)

print(x + x)
# [[ 2  4  6]
#  [ 8 10 12]]

print(x - x)
# [[0 0 0]
#  [0 0 0]]

print(x / x)
# [[1. 1. 1.]
#  [1. 1. 1.]]

print(x ** x)
# [[    1     4    27]
#  [  256  3125 46656]]


[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[    1     4    27]
 [  256  3125 46656]]
